<?php

namespace App\Http\Controllers\Provision;

use App\Http\Controllers\Controller;
use App\Models\Router;
use App\Services\Provisioning\ProvisionTokenService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\Response;

class ProvisionController extends Controller
{
    public function script(string $token, ProvisionTokenService $tokens): Response
    {
        $tokenRow = $tokens->findValidByRawToken($token);

        if (!$tokenRow) {
            return response("Invalid or expired token.\n", 404, ['Content-Type' => 'text/plain']);
        }

        // One-time use: mark used immediately (prevents reuse)
        $tokens->markUsed($tokenRow);

        $router = $tokenRow->router;

        // Generate router API creds (system_api user)
        $apiUser = 'system_api';
        $apiPass = \Illuminate\Support\Str::random(16); // safe random password (no special chars)

        // Store encrypted password (Laravel encrypt)
        $router->forceFill([
            'api_user' => $apiUser,
            'api_pass_enc' => encrypt($apiPass),
            'status' => 'pending',
            'last_error' => null,
        ])->save();

        // IMPORTANT: Server IP allowed to access MikroTik API
        // (use env so you can change later)
        $serverIp = config('app.router_server_ip', 'YOUR_SERVER_IP');

        // Callback URL (router will call back after importing)
        $callback = route('router.callback', [], false); // relative path
        $callbackFull = rtrim(config('app.url'), '/') . $callback;

        // Build RouterOS script
        $script = $this->buildBootstrapScript(
            identity: $router->identity,
            apiUser: $apiUser,
            apiPass: $apiPass,
            serverIp: $serverIp,
            callbackUrl: $callbackFull
        );

        return response($script, 200, ['Content-Type' => 'text/plain']);
    }

    public function callback(Request $request): Response
    {
        // Minimal callback: router reports it's done
        $identity = $request->query('identity');
        $mgmtIp   = $request->query('ip'); // optional, can be sent by router

        if (!$identity) {
            return response("missing identity\n", 400);
        }

        $router = Router::where('identity', $identity)->first();
        if (!$router) {
            return response("router not found\n", 404);
        }

        $router->forceFill([
            'mgmt_ip' => $mgmtIp ?: $router->mgmt_ip,
            'status' => 'connected',
            'last_seen_at' => now(),
        ])->save();

        return response("ok\n", 200, ['Content-Type' => 'text/plain']);
    }

    private function buildBootstrapScript(
        string $identity,
        string $apiUser,
        string $apiPass,
        string $serverIp,
        string $callbackUrl
    ): string {
        // NOTE: RouterOS needs escaped quotes properly
        $identityEsc = str_replace('"', '\"', $identity);

        return <<<ROS
# === Provisioning Bootstrap Script (generated by Laravel) ===
# Router Identity: {$identityEsc}

:log info "Provisioning started for identity={$identityEsc}";

# Create API user (idempotent: if exists, just set password)
:if ([:len [/user find name="{$apiUser}"]] = 0) do={
  /user add name="{$apiUser}" group=full password="{$apiPass}";
} else={
  /user set [/user find name="{$apiUser}"] password="{$apiPass}";
}

# Enable API service and set port
/ip service enable api
/ip service set api port=8728

# Firewall: allow API only from your server
# (basic rule; you can refine chain/order later)
:if ([:len [/ip firewall filter find chain=input protocol=tcp dst-port=8728 src-address="{$serverIp}" action=accept]] = 0) do={
  /ip firewall filter add chain=input protocol=tcp dst-port=8728 src-address="{$serverIp}" action=accept comment="Allow API from server";
}

# (Optional) drop others to protect API (enable if you want strict)
# /ip firewall filter add chain=input protocol=tcp dst-port=8728 action=drop comment="Drop API from others"

# Notify system (callback)
:log info "Calling back to system...";
/tool fetch keep-result=no url="{$callbackUrl}?identity={$identityEsc}&ip=\$[/ip address get [find interface~\\"ether\\"] address]"

:log info "Provisioning finished.";
ROS;
    }
}
